### ISSUE TITLE
Adding binary optimizer (Bop) documentation 

### ISSUE THREAD

**Issue by arashb** [larq/larq#105]
- [ ] enhancing Bop documentation in code
- [ ] adding Bop documentation/tutorial to [Larq official documentation page](https://plumerai.github.io/larq/)

**Comment by goodship1** [comment]
is it ok to pick this issue up ?

**Comment by koenhelwegen** [comment]
Hi @goodship1 - that would be great! Let us know if you need any help.

**Comment by koenhelwegen** [comment]
I expanded the API documentation, a full tutorial would be nice but not necessary right now I think (note Bop is already mentioned in the [training guide](https://larq.dev/guides/bnn-optimization/)).

@goodship1 feel free to comment or make a PR if you've been working on this!
