### ISSUE TITLE
Warning that may come from tensorflow.

### ISSUE THREAD

**Issue by appleleaves** [larq/larq#175]
When using the lqz train scrips to train a model, warning occurs:

2019-08-08 09:57:39.617846: W tensorflow/core/grappler/utils/graph_view.cc:830] No registered 'MultiDeviceIteratorFromStringHandle' OpKernel for GPU devices compatible with node {{node MultiDeviceIteratorFromStringHandle}}
	.  Registered:  device='CPU'

2019-08-08 09:57:39.618112: W tensorflow/core/grappler/utils/graph_view.cc:830] No registered 'MultiDeviceIteratorGetNextFromShard' OpKernel for GPU devices compatible with node {{node MultiDeviceIteratorGetNextFromShard}}
	.  Registered:  device='CPU'

I wonder if you have met the same problem and give me some suggestions.
Thanks!

### Environment

TensorFlow version: 2.0.0b1
Larq version: 0.6.0

**Comment by lgeiger** [comment]
This warning comes from TensorFlow 2.0.0b1 and is related to the multi GPU distribution strategy.

Downgrading to the latest stable version 1.14.0 will remove the warning. Version 2.0.0rc1 which should be released soon might fix this too.

**Comment by StanleyGan** [comment]
I am using TensorFlow 1.15.0 and also encountered this error. Is this normal?

**Comment by lgeiger** [comment]
> I am using TensorFlow 1.15.0 and also encountered this error. Is this normal?

I haven't encountered this error in TensorFlow 2.0.0. Though it looks like this is an issue with TensorFlow 1.15: https://github.com/tensorflow/tensorflow/issues/35384

Sadly I think there is not much we can do about this on the larq side.

**Comment by stanleyG4t1qbit** [comment]
Thanks for your reply! May you elaborate on the effect of this on multi-gpu strategy?

**Comment by StanleyGan** [comment]
Thanks for your reply! May I know what is the effect of this on multi-gpu strategy?

**Comment by lgeiger** [comment]
> May you elaborate on the effect of this on multi-gpu strategy?

This looks like to be an issue with TensorFlow 1.15 which doesn't seem to be related to larq it self (https://github.com/tensorflow/tensorflow/issues/35384), so unfortunately I cannot really elaborate on that.

Do you run into the same issue with TensorFlow 1.14 or 2.0.0?

**Comment by greatjus** [comment]
I meet the same issue and it was fix when i turn on the eager-mode in TensorFlow 2.0, which I've turn off before.

**Comment by marchss** [comment]
TF 2.2.0 still has this issue when using distributed MultiWorkerMirroredStrategy
