### ISSUE TITLE
model summery trainable params

### ISSUE THREAD

**Issue by appleleaves** [larq/larq#179]
If you set a keras.layers.Conv2D(...trainable=False), the lq.models.summery(model) report a wrong non-trainable number(and claim the non-trainable params trainable.)
Using model.summery can get the right answer.

I should be right, but please check it to confirm it again by yourself.

**Comment by lgeiger** [comment]
That's interesting, it looks like TensorFlow marks the weights as trainable even if they are listed as non trainable variables:
```python-console
In [19]: model = keras.Sequential([keras.layers.Conv2D(16, 3, input_shape=(32, 32, 3), trainable=False)])                                                   

In [20]: model.layers[0].non_trainable_weights[0].trainable                                                                                                 
Out[20]: True
```
See also here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/core.py#L1014-L1030

I'll take a look to see if there is a quick fix.
