### ISSUE TITLE
GPU volatile GPU-Util remains 0

### ISSUE THREAD

**Issue by appleleaves** [larq/larq#184]
### Feature description
When running the training code, the volatile GPU-Util remains 0.

tensorflow version is 1.14.0
others like larq are up-to-date.

**Comment by lgeiger** [comment]
Make sure to install `tensorflow-gpu==1.14.0` since `tensorflow==1.14.0` only ships with CPU support: https://www.tensorflow.org/install/gpu

**Comment by appleleaves** [comment]
I am using the tensorflow-gpu==1.14.0.
When running the cifar10 examples, it works fine.
But when trianing with imagenet using command line lqz train ...., the volatile GPU-Util remains 0, and it takes too much time to train.

**Comment by jamescook106** [comment]
Are you training one of the examples? And if so which one? If not, would you provide more details as to what you are doing?

**Comment by appleleaves** [comment]
The memory in the GPUs are taken by the training program.
I train the birealnet. But I think it's not about which net we are using.
When I use the examples in the https://larq.dev/examples/binarynet_cifar10, it works fine.

But when train birealnet on imagenet, the process takes memory like the  binarynet_cifar10 process, but the volatile GPU-Util remains 0.

**Comment by appleleaves** [comment]
I use CUDA 10.0 and cudnn 7.4.The GPU cards are 1080ti*4.

**Comment by jamescook106** [comment]
- Okay, so to confirm, you are running the default hyperparameters for the birealnet example? 
- Have you managed to run 1 epoch? How long did it take?
- Are any of the GPUs utilised?

**Comment by appleleaves** [comment]
Default setting,yes.
About 200mins for 1 epoch.
The gpus memory is taken,but thevolatile remain 0.

发自叶剑鸣

**Comment by jamescook106** [comment]
200 mins for an epoch seems unreasonable, is your tensorflow-gpu distribution working? Can you try running a CIFAR10 (or imagenet) experiment without using Larq Zoo to test it?

**Comment by jamescook106** [comment]
@appleleaves was this resolved for you? Did you perform the above test?

**Comment by lgeiger** [comment]
Closing, due to inactivity. @appleleaves Feel free to reopen if this is still an issue.
