### ISSUE TITLE
What are the files in the zookeeper-logs stand for?

### ISSUE THREAD

**Issue by appleleaves** [larq/larq#186]

**Comment by timdebruin** [comment]
The `zookeeper-logs` directory is the [default output directory ](https://github.com/larq/zookeeper/blob/1210127673e3c4a9bd1ec1bcdc4fc6200b16797d/zookeeper/cli.py#L54-L58) when using the [zookeeper](https://github.com/larq/zookeeper) cli to run an experiment. It contains outputs such as tensorboard logs and model checkpoints.
