### ISSUE TITLE
Documentation (Regarding to JOSS review)

### ISSUE THREAD

**Issue by EduPH** [larq/larq#246]
Some suggestions:
In the quantizers documentation:
1. It seems that SteSign/ste_sign (if they are the same) is repeated twice [here](https://larq.dev/api/quantizers/#ste_sign). The same for swish_sign/SwishSign.
2. These quantizers (magnitude_aware_sign,swish_sign)have no formula, nor description.

**Comment by lgeiger** [comment]
Thanks for the suggestions. The feedback is really valuable for us 👍 

> 1. It seems that SteSign/ste_sign (if they are the same) is repeated twice here. The same for swish_sign/SwishSign.

Indeed they are computing the same thing. The difference is the usage. Larq allows three different usage patterns outlined [here](https://larq.dev/api/quantizers/#larqquantizers):
1. In a larq layer the quantizer can be referenced with a string. Compare `kernel_quantizer="ste_sign"` and `activation="relu"`.
2. The quantizer can also be called as a function. Compare `kernel_quantizer=lq.quantizers.ste_sign` and `activation=tf.nn.relu`.
3. If the default arguments of the quantizer need to be configured, it is important that the quantizer class is serializable. That means the quantizer should be called like `kernel_quantizer=lq.quantizers.SteSign(clip_value=1.25)` similar to `kernel_constraint=tf.keras.constraints.MaxNorm(max_value=2)`

Options 1 and 2 are really only here for ease of use. What we could do though is remove option 2 and replace it with `kernel_quantizer=lq.quantizers.ste_sign()` which would than mimik [Keras Constraints](https://keras.io/constraints/) and would only require us to alias `ste_sign` to `SteSign` so both would be classes which would make implementation simpler and usage consistent as well.

Though I am not sure if people would expect quantizers to be used like activations.
@EduPH @koenhelwegen @timdebruin @AdamHillier What do you think?

> 2. These quantizers (magnitude_aware_sign,swish_sign)have no formula, nor description.

I added more docs and formulas in #257

**Comment by EduPH** [comment]
I think that it is natural to use them as activation functions. However, if you prefer to keep as it is now, at least it should be clearer on the documentation and unified in some sense. Maybe you could combine both definitions and include the different ways to use them together. I haven't got strong opposition to any option you decide to choose.

**Comment by lgeiger** [comment]
> I think that it is natural to use them as activation functions. However, if you prefer to keep as it is now, at least it should be clearer on the documentation and unified in some sense. Maybe you could combine both definitions and include the different ways to use them together. I haven't got strong opposition to any option you decide to choose.

I have to think about this a bit more, of what makes sense. For now I reordered the API docs to make the distinction clearer: #274
