### ISSUE TITLE
Disable custom metrics for multi-gpu on TF 1.14.0 to prevent it from crashing

### ISSUE THREAD

**Issue by jneeven** [larq/larq#251]
### Feature motivation
See [this issue](https://github.com/larq/larq/issues/155). 

### Feature description
When adding custom metrics (i.e. flip_ratio or gradient_flow) to any layer, check that we're not currently in multi-gpu mode and using tf 1.14.0 at the same time, to prevent tensorflow from raising an undescriptive error later on.

**Comment by lgeiger** [comment]
Since this is a TensorFlow error which is fixed in TF 1.15.0, 2.0.0 and 2.1.0
I think we can close this.
