### ISSUE TITLE
Make the HyperparameterScheduler compatible with the CaseOptimizer

### ISSUE THREAD

**Issue by MariaHeuss** [larq/larq#347]
### Feature motivation
The HyperparameterScheduler is not compatible with the CaseOptimizer since the hyperparameters are attributes of the optimizers inside the CaseOptimizer. 

### Feature description
I propose one of the two possible solutions: 
Either we could give HyperparameterScheduler the optimizer as an argument. It could be called via ```  HyperparameterScheduler(schedule, hyperparameter, optimizer, verbose=0) ``` and the right optimizer inside the CaseOptimizer can be addressed. (@koenhelwegen) 

My second proposal would be to search the CaseOptimizer for optimizers that have the hyperparameter as attribute. Then the schedule can be applied to this optimizer only. The downside of this would be that in case there are two optimizers inside the CaseOptimizer that have a hyperparameter with the same name the schedule would be applied to both of them. I do not think this would happen very often but it could definitively be an issue. See code below for my second proposal. 
### Feature implementation
``` python 
class HyperparameterScheduler(tf.keras.callbacks.Callback):
    """Generic hyperparameter scheduler.
    # Arguments
    schedule: a function that takes an epoch index as input
        (integer, indexed from 0) and returns a new hyperparameter as output.
    hyperparameter: str. the name of the hyperparameter to be scheduled.
    verbose: int. 0: quiet, 1: update messages.
    """

    def __init__(self, schedule, hyperparameter, verbose=0):
        super(HyperparameterScheduler, self).__init__()
        self.schedule = schedule
        self.hyperparameter = hyperparameter
        self.verbose = verbose

    def on_epoch_begin(self, epoch, logs=None):
        for op in self.model.optimizer.optimizers:
            if hasattr(op, self.hyperparameter):

                hp = getattr(op, self.hyperparameter)
                try:  # new API
                    hyperparameter_val = tf.keras.backend.get_value(hp)
                    hyperparameter_val = self.schedule(epoch, hyperparameter_val)
                except TypeError:  # Support for old API for backward compatibility
                    hyperparameter_val = self.schedule(epoch)

                tf.keras.backend.set_value(hp, hyperparameter_val)

                if self.verbose > 0:
                    print(
                        f"Epoch {epoch + 1}: {self.hyperparameter} changning to {tf.keras.backend.get_value(hp)}."
                    )

    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}
        for op in self.model.optimizer.optimizers:
            if hasattr(op, self.hyperparameter):
                hp = getattr(op, self.hyperparameter)
                logs[self.hyperparameter] = tf.keras.backend.get_value(hp)
```

**Comment by leonoverweel** [comment]
I'm leaning towards the first option because it's a bit more explicit in what's happening; but one drawback could be that I'm not sure if/how it'd work when the optimizers get reloaded on an experiment restart/resume. So I'm also good with doing option two if we document it well.

**Comment by MariaHeuss** [comment]
Resuming and Restarting works fine with the first option. I am leaning to the first option as well since it gives more flexibility. I will make a PR.
