### ISSUE TITLE
Change default hyperparameters of Bop

### ISSUE THREAD

**Issue by lgeiger** [larq/larq#361]
The default hyperparameters for Bop are not really optimal (i.e. gamma is probably too high for most task): `Bop(threshold=1e-07, gamma=0.01, name='Bop', **kwargs)`

For example in our [paper](https://papers.nips.cc/paper/8971-latent-weights-do-not-exist-rethinking-binarized-neural-network-optimization.pdf) we used a gamma decayed from 1e-4 to 1e-6 and a threshold of 1e-8 for the ImageNet experiments.

I think we should update the default parameters to a more sensible choice. @MariaHeuss What do you think?

**Comment by MariaHeuss** [comment]
Yes, I agree that we should change the default. The values that you are mentioning are working well for a variety of models, although sometimes letting gamma start at 3e-4 works even better. I would set the threshold to 1e-8 and gamma to 1e-4 by default. I can make a PR later.
