### ISSUE TITLE
Get quantized weights

### ISSUE THREAD

**Issue by gdomenech1** [larq/larq#406]
Hi,
I am new both in tf and larq, so my question might sound a beginners'one. I find this library very useful, but I am unabble to get the quantized weigths once the dnn training has finished. I've tried with the first introductory example, but when I call get_weights() I obtaing floating values, so I guess I am doing something wrong. How could I obtain the  quantized weight values?
Thanks in advance

**Comment by leonoverweel** [comment]
Hey @gdomenech1, thanks for taking a look at Larq!

I'm guessing you trained your model with a latent weights optimizer like SGD or Adam (e.g. following [our BNN training guide](https://larq.dev/guides/bnn-optimization/) and not with [Bop](https://larq.dev/api/optimizers/#bop)). In this case, Larq internally keeps your weights as full-precision numbers and quantizes them by passing them through [Quantizers](https://larq.dev/api/quantizers) on the forward pass. When you call `get_weights()`, you get these full-precision "latent" weights.

We've been working on making it easier to access the quantized weights in a version of Larq that hasn't been released to PyPI yet. If you install Larq from `master`, though, you should be able to use a `quantized_scope` to access them; see [this comment](https://github.com/larq/larq/issues/360#issuecomment-567044374) (and the rest of that issue for context).

Does this work for you?

**Comment by gdomenech1** [comment]
Hello,

thanks for the fast answer. I guess that if,  once the network is trained, I "manually" convert the full precission weights obtained through get_weight(), follwing the last comment you linked, (so that any latent weight < 0 becomes -1 and any >= 0 becomes +1), I will obtain the binarized weights, is that guess right?
And if so, could I use also a simmilar procedure if I use the DOReFaQuantizier for K bits (taking into account of course its quantization function) ?

Thanks in advance

**Comment by leonoverweel** [comment]
@gdomenech1, yep, that's exactly right!

I'll close this issue since it looks like we've resolved your question. If not, feel free to reopen.
