### ISSUE TITLE
Improve and expand model summary reports.

### ISSUE THREAD

**Issue by TarasIakymchuk** [larq/larq#441]
### Feature motivation
The existing model summary does not provide sufficient data to recreate full model topology from it and is inconvenient for analysis.
Typical data I often need:

- What is the ratio of DW convolution operations in this model?
- How much memory is required for intermediate variables in this model? (non-trivial for DenseNets).
- What maximum stride does this model have?

It's hard to extract this information now, and many less popular features can't be unambiguously described. For example, current model summary can't properly describe grouped convolutions. 

### Feature description
I suggest the following set of fields in the model summary:

1. Layer number. This is an incremental counter. Input data are considered to be Layer 0.
2. Layer type. This is ENUM defining the type of the layer (conv, dwconv, add, bn, relu etc). Currently, layers are named as "layertype_layernumber" with layernumber starting from 2. It's very inconvenient for filtering by type so I suggest splitting name and number into two fields.
3. Weight precision.
4. Activation precision. This is for the future support of asymmetric quantization.
5. Output XY dimension. If it may be necessary, we can split it into X and Y fields to describe non-square FMs.
6. Output Z dimension (number of kernels).
7. Kernel X dimension. Always 1 for non-conv operations. For pooling, it describes pool size.
8. Kernel Y dimension. Always 1 for non-conv operations. For pooling, it describes pool size.
9. Kernel Z dimension. 
10. The number of parameters (weights).
11. The number of elementary operations. For convolution layers, its the number of MACs, for GAP or skip connection merges it's the number of additions. For activation functions or BN it's the number of activations. For concatenation, it's 0.
12. The number of all intermediate parameters. This is the total amount of intermediate data that will be used in the next layers. 
13. Comment or label. This field used as a label to mark the activations used in skip connections, or verbal description of the layer.
Layer types:

1. Conv. This includes pointwise and dilated convolutions.
2. Fully connected.
3. PWconv. Technically it's Conv with kernel Z dimension of 1. It is considered a separate layer type because it is executed in HW in a different way.
4. Activation layer (relu, selu, elu).
5. BN layer.
6. Store. Pseudo-layer indicating that the output of the previous layer is stored for future use (skip connection.
7. Add. This layer performs pointwise addition of the outputs from the previous layer with the activations stored by layer reported in field 13. 
8. Average pooling.
9. Global pooling.
10. Pointwise multiplication. Used for example for Squeeze&Excite blocks. Field 13 describes the number of the layer which outputs are used as the second multiplicand.
11. Concatenation. Field 13 describes the number of the layer which outputs are appended.

### Feature implementation
The model summary should be generated in the CSV format. This is convenient for humans as well as for all kinds of automatic tools. For example, the compiler can use this summary to arrange memory regions for the activations.

**Comment by jneeven** [comment]
> The model summary should be generated in the CSV format. This is convenient for humans as well as for all kinds of automatic tools.
Doesn't JSON make more sense? It's much more readable, and at least you can "display" shapes of arbitrary dimensions rather than setting "empty" dimensions for e.g. 1D convolutions

**Comment by TarasIakymchuk** [comment]
JSON is not understood by spreadsheets and much harder to read without dedicated SW.

**Comment by jneeven** [comment]
To prevent "overloading" the Larq model summary with information, these changes are better suited for an additional extended summary tool. Closing this issue as it has been moved to another repo.
