### ISSUE TITLE
Add int8 quantized size to model summary

### ISSUE THREAD

**Issue by leonoverweel** [larq/larq#448]
### Feature motivation
Our model summary currently reports the following two metrics for model size:

```
| Model size:                        151.80 KiB |
| Float-32 Equivalent                158.91 KiB |
```

This is calculated as follows for models that contain both binary and full precision (FP) weights:

| Metric | Binary weights | FP weights |
| --- | --- | --- |
| `Model size` | counted as 1 bit | counted as 32 bits |
| `Float-32 Equivalent` | counted as 32 bits | counted as 32 bits |

For models in which FP weights will be 8-bit quantized for inference, it'd be useful to also know how large that model would be.

### Feature description
I propose adding another metric to the model summary:

| Metric | bin weights | FP weights |
| --- | --- | --- |
| `int-8 quantized equivalent` | counted as 1 bit | counted as 8 bits |

### Feature implementation
Adding another property to [`ModelProfile`](https://github.com/larq/larq/blob/master/larq/models.py#L242), similar to:

```python
    @property
    def fp_equivalent_memory(self) -> int:
        return sum(l.fp_equivalent_memory for l in self.layer_profiles)
```

And then adding it to the model summary printout.

**Comment by koenhelwegen** [comment]
Yes would be  a useful feature! I would call it `Model size (max bits/param=8)` or something like that though, to me `int-8 quantized` suggests binary weights are counted as 8-bit as well.
