### ISSUE TITLE
Inconsistent quantiser names

### ISSUE THREAD

**Issue by AdamHillier** [larq/larq#467]
This is very minor and I'm very happy for this to be a `wontfix`.

At the moment two out of eight quantizers have a "Quantizer" suffix:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/7688302/77927969-c04f2400-729f-11ea-8e3d-d04c8d85367f.png">
It seems to me it should be all of them with the suffix or none of them with the suffix. We could potentially standardise on one version but have an alias to the other version.

**Comment by leonoverweel** [comment]
I have a slight preference to dropping the suffixes for the two that have them, but no strong opinion. Also in favor of standardizing.

**Comment by lgeiger** [comment]
I agree, I'm in favour of standardising as well :+1:
I think dropping the suffix makes the most sense since the quantizers will likely be used as `lq.quantizers.*`.

**Comment by AdamHillier** [comment]
Would you want to add an alias for the two that would change so that this wouldn't be a breaking change?

**Comment by lgeiger** [comment]
> Would you want to add an alias for the two that would change so that this wouldn't be a breaking change?

I think I'd prefer that for now, since it's not much work.
We can remove the alias for good when we have to make some breaking changes elsewhere.

**Comment by leonoverweel** [comment]
Should we keep this open until it's merged from @AdamHillier's fork into larq/larq?

**Comment by leonoverweel** [comment]
Oops, got confused by GitHub UI and didn't notice #468. Nothing to see here. 😅
