### ISSUE TITLE
Can we training precisions higher than 1-bit ? 

### ISSUE THREAD

**Issue by powderluv** [larq/larq#477]
Can Larq support training low precision networks larger than 1-bit ? What would it take to extend larq for that ? 

Thanks

**Comment by lgeiger** [comment]
> Can Larq support training low precision networks larger than 1-bit ?

Absolutely! The larq layers can be used for arbitrary precisions.

> What would it take to extend larq for that?

We currently include the [dorefa-net quantizer](https://docs.larq.dev/larq/api/quantizers/#dorefa) which can be used for arbitrary bit-widths and a [ternary quantizer](https://docs.larq.dev/larq/api/quantizers/#stetern).
Larq also supports [custom quantizers](https://docs.larq.dev/larq/guides/key-concepts/#using-custom-quantizers) which can be simple functions or full keras layers with optional learnable parameters.

@powderluv What precision do you need for your use case?

**Comment by powderluv** [comment]
Ideally I'd like to use it for an FP8 (1,5,2) network but that may change to lower than that.

**Comment by lgeiger** [comment]
> Ideally I'd like to use it for an FP8 (1,5,2) network but that may change to lower than that.

Sounds great! The `DoReFa` quantizer should get you started there.

We just added support for 8-bit to our binary kernels in [Larq Compute Engine](https://docs.larq.dev/compute-engine) and will probably start integrating end2end support for 8-bit layers into larq soon that can be used to deploy the networks using Larq Compute Engine and TFLite. Currently Larq Compute Engine only supports 1-bit and float operations in a straight forward way.

**Comment by powderluv** [comment]
Awesome will take a look at it and report back. 

When you add 8-bit support for the compute engine will it include a low precision dialect for MLIR ? If so would it be generic enough for other precisions ?

**Comment by lgeiger** [comment]
> Ideally I'd like to use it for an FP8 (1,5,2) network but that may change to lower than that.

Ah sorry I misread your comment. We only looked into `int8`. I think you would need to write a custom quantizer for FP8 then.

> When you add 8-bit support for the compute engine will it include a low precision dialect for MLIR? If so would it be generic enough for other precisions?

This is not something we have planned. Larq Compute Engine focuses on 1-bit deployment, though it can be used in combination with any existing TFLite float32 or int-8 op. That means we will export the network in the TFLite flatbuffer format to be compatible with the TFLite runtime.
I thought about building ontop of the MLIR quantization dialect and introduce a custom LCE dialect as an implementation detail some time ago but we haven't pursued it to keep things simple. I can report back once we have a concrete plan, but we will likely follow the way TFLite currently handles int-8 quantization. If I recall correctly the MLIR based quantization setup is still experimental there.

We're definitely open to explore new approaches for this though. Could you tell us a bit more about your use case? I.e. do you have a particular hardware in mind, and what would your desired workflow for using larq and larq compute engine be?
(Feel free to reach out me on https://spectrum.chat/larq if you don't want to share this information publicly)

**Comment by powderluv** [comment]
thanks. Yeah the MLIR setup is very much in flux and now we have TFRT to look forward too. 

We have a similar stack to what you have but use FP8 (or other low precision FPs). I was trying to leverage as much of community work as possible to avoid investing time in those areas if possible and less about using larq as is since our workloads will require higher accuracy.

**Comment by lgeiger** [comment]
> Yeah the MLIR setup is very much in flux and now we have TFRT to look forward too.

I agree. MLIR, the upcoming TFRT and [IREE](https://github.com/google/iree) are all very interesting.

> I was trying to leverage as much of community work as possible to avoid investing time in those areas if possible and less about using larq as is.

Sounds great, in general we're very happy to accept PRs that make larq more flexible for other bit-widths or encourage new projects that built on top of `larq`.

**Comment by powderluv** [comment]
Will keep you guys posted on our work and if we can leverage yours. Thanks.
