### ISSUE TITLE
New Quantizer "ClipAndQuantize" derived from DoReFa 

### ISSUE THREAD

**Issue by FerranLisa** [larq/larq#483]
### Feature motivation

Current DoReFa quantizer is limited to [0,1] activations, and actually seems to have a bug in the quantization formula

### Feature description

New quantizer "ClipAndQuantize" is an improved version for any range [minValue, maxValue]

### Feature implementation

```python
class ClipAndQuantize(lq.quantizers.BaseQuantizer):
    """Clips in range [minValue, maxValue] and quantizes to k_bit fixed point binary """

    def __init__(self, minValue: float =-1.0, maxValue: float = +1.0, k_bit: int = 4, **kwargs):
        self.minValue=minValue
        self.maxValue=maxValue
        self.precision=k_bit
        super().__init__(**kwargs)

    def call(self, inputs):
        inputs = tf.clip_by_value(inputs, self.minValue, self.maxValue)

        @tf.custom_gradient
        def _k_bit_with_identity_grad(x):
            n = 2 ** self.precision
            xQuantized=tf.round(x * n) / n
            return xQuantized, lambda dy: dy

        outputs = _k_bit_with_identity_grad(inputs)
        return super().call(outputs)

    def get_config(self):
        return {**super().get_config(), "minValue": self.minValue, "maxValue": self.maxValue, "k_bit": self.precision}
```

**Comment by FerranLisa** [comment]
I apologize by claiming DoReFa to have a bug. It is actually correct for that particular implementation uniformly distributing values like {0, 1/3, 2/3, 1}
This new quantizer is actually aimed to use in ternary-like networks, where values are distributed as {-1, -1/2, 0, +1/2, +1}
I am a hardware engineer so using fractional values like 1/3, 1/7, 1/5, etc. is not acceptable for my application because it has the lowest efficiency in terms of power consumption and silicon area. The proposed quantizer uses combinations of power-of-two values, so MAC operations are straight-forward in custom hardware.
For clarity I suggest naming this quantizer "**TernaryClipAndQuantize**" (although minValue and maxValue aren't really constrained to -1 and +1)

**Comment by koenhelwegen** [comment]
Hi, don't worry about the bug report and it's great to see Larq is useful for your project and that you're looking to contribute back!

I'm not sure if the proposed quantizer would provide the intended behaviour though. You mention five values for ternary, while two bits can encode at most four (it is common to only use three like in [SteTern](https://docs.larq.dev/larq/api/quantizers/#stetern) for the issues you raise). Two minor things are that I think you want to use ``n = 2 ** (self.precision - 1)`` and that the scaling with min and max should be taken into account during quantization.

I would recommend having a look at section 2.1 of the DoReFa paper to get more details into how it can be executed efficiently in hardware.

Please let me know if I'm missing something!

**Comment by FerranLisa** [comment]
Hi Koen,
I realize my use case is a bit out of what is normally considered in DNN implementations, and I feel it is a bit out of the scope of a Github issue.
I think this requires a more general discussion in Spectrum, so I will close this issue for the moment.
