### ISSUE TITLE
Memory reduction not seen when using LARQ 

### ISSUE THREAD

**Issue by jain-harshil** [larq/larq#508]
Hi, I am using the larq Conv1D model for text classification and then wishing to compare it with the non-binarized Keras version for changes in memory usage. Since larq uses 1 bit for storing the +1 or -1, ideally the memory usage should reduce. However,  I cannot see any reduction on my NVIDIA Tesla GPU. Could someone please help me out with this?

**Comment by koenhelwegen** [comment]
During training the model is not actually binary. "Latent" float32 weights are used to accumulate the small update steps from gradient descent and only binarized on the forward pass.

During inference the model will be smaller. You can use [`lce.convert_keras_model`](https://docs.larq.dev/compute-engine/api/converter/#convert_keras_model-function) to convert the model and learn more about deploying BNNs with LCE [here](https://docs.larq.dev/compute-engine/).

**Comment by jain-harshil** [comment]
But it says here (https://docs.larq.dev/) that a 1-bit model is initialized. Could you please clarify?

**Comment by koenhelwegen** [comment]
The training procedure for BNNs is explained in a bit more detail here: https://docs.larq.dev/larq/guides/bnn-optimization/.

But the key point is that the efficiency gain for BNNs is specific to inference, not training (in fact BNNs are often harder too train and require more compute here).

Let me know if you've any more questions or anything in the guide is unclear.

**Comment by jain-harshil** [comment]
I have one more issue. While saving the binary weights, I do not see any reduction in the size of h5 files when compared to same configuration non binarized keras model. While printing summary of the model, it shows the size of the model, but I don't get the same size when I save the weights. 
![received_647235556003467](https://user-images.githubusercontent.com/44444697/85798478-2c381000-b75b-11ea-919c-aa758bdf0ca9.jpeg)

**Comment by koenhelwegen** [comment]
This is expected, the `.h5` file contains the float32 latent weights (e.g. it may be used for checkpointing during training, so we want to keep all the data).

Once training is finished, you can convert the model to a `tflite` file using the LCE function I referenced above. You will find the `tflite` file has the size you expect.

**Comment by jain-harshil** [comment]
I have used this for saving https://docs.larq.dev/larq/api/context/

**Comment by koenhelwegen** [comment]
Ah I see, yes in that case the weights are passed through a sign first but the representation is still float32. If you inspect the h5 file, you will find the weights to have the values -1.0000... and 1.0000.... On the training side (which is what Larq is targeting) any quantization is really 'fake' quantization, similar to the way TF handles int8 quantization (eg [here](https://www.tensorflow.org/api_docs/python/tf/quantization/fake_quant_with_min_max_args?version=nightly)).

**Comment by jain-harshil** [comment]
Ok, so the size mentioned is of the tflite file which is obtained after converting the h5 file obtained during training? Am I correct?

**Comment by jain-harshil** [comment]
tflite_model = convert_keras_model(model)
with open("/tmp/my_model.tflite", "wb") as f:
    f.write(tflite_model)

The model argument on the first line is the h5 file right?

**Comment by jain-harshil** [comment]
Also, coild you please help as to how to do inference in keras with the tflite file?

**Comment by koenhelwegen** [comment]
Please have a look at the [LCE documentation](https://docs.larq.dev/compute-engine/), that should answer both of these questions. I'll close this issue as the original question is resolved.

**Comment by jain-harshil** [comment]
```
import larq_compute_engine as lce
import tensorflow as tf

tf.compat.v1.enable_eager_execution()

tflite_model = lce.convert_keras_model("./mnist_binary.h5")
with open("./mnist_binary.tflite", "wb") as f:
    f.write(tflite_model)
```

I am getting a tensorflow eagerly error.

After enabling eagerly, I get this error

`AttributeError: 'str' object has no attribute 'call'`

**Comment by jain-harshil** [comment]
Its a humble request to resolve this error

**Comment by lgeiger** [comment]
> After enabling eagerly, I get this error

@jain-harshil [`lce.convert_keras_model`](https://docs.larq.dev/compute-engine/api/converter/#convert_keras_model-function) expects a Keras model as the first argument and not a filepath. I made a PR to raise an actionable error message in https://github.com/larq/compute-engine/pull/414 when wrong arguments are passed to the function.

**Comment by jain-harshil** [comment]
Thanks a lot Lucas @lgeiger. Much appreciated!!

**Comment by Sreerag-ibtl** [comment]
> This is expected, the `.h5` file contains the float32 latent weights (e.g. it may be used for checkpointing during training, so we want to keep all the data).
> 
> Once training is finished, you can convert the model to a `tflite` file using the LCE function I referenced above. You will find the `tflite` file has the size you expect.

@koenhelwegen Have a doubt here. Does this mean, one must always use lce to get the performance gain of larq trained model?

**Comment by koenhelwegen** [comment]
Yes that's correct, Larq is intended for training, only by using LCE you will be able to take advantage of the reduced model size and lower latency. At some point we may invest in speeding up at least the forward pass during training as well, but this is currently low on our priority list.

**Comment by Sreerag-ibtl** [comment]
> Yes that's correct, Larq is intended for training, only by using LCE you will be able to take advantage of the reduced model size and lower latency. At some point we may invest in speeding up at least the forward pass during training as well, but this is currently low on our priority list.

@koenhelwegen Can I update the readme with this specific info about the importance of LCE and make a PR?

**Comment by leonoverweel** [comment]
@Sreerag-ibtl thanks for the suggestion; since we're pretty specific about how we talk about LCE/Larq, I thought it was more efficient to make the PR myself; see above.
