### ISSUE TITLE
conversion to tflite error

### ISSUE THREAD

**Issue by jain-harshil** [larq/larq#509]
```
import larq_compute_engine as lce
import tensorflow as tf

tf.compat.v1.enable_eager_execution()

tflite_model = lce.convert_keras_model("./mnist_binary.h5")
with open("./mnist_binary.tflite", "wb") as f:
    f.write(tflite_model)
```

I am getting a tensorflow eagerly error.

After enabling eagerly, I get this error

`AttributeError: 'str' object has no attribute 'call'`

**Comment by jain-harshil** [comment]
![85798478-2c381000-b75b-11ea-919c-aa758bdf0ca9](https://user-images.githubusercontent.com/44444697/85838897-dd6c9380-b7b7-11ea-9761-754b5196994d.jpeg)

How do I download 8 bit precision weights?

**Comment by Tombana** [comment]
> ```
> tflite_model = lce.convert_keras_model("./mnist_binary.h5")
> ```
> `AttributeError: 'str' object has no attribute 'call'`

The function `convert_keras_model` expects a keras model, not a path to an `.h5` file. So first load the `.h5` file using Keras functions (for example `model = tf.keras.models.load_model("mnist_binary.h5")`) and then run `lce.convert_keras_model(model)` .

**Comment by jain-harshil** [comment]
Thanks a lot.  One last question. How do I download 8-bit precision weights?

**Comment by jain-harshil** [comment]
> > ```
> > tflite_model = lce.convert_keras_model("./mnist_binary.h5")
> > ```
> > 
> > 
> > `AttributeError: 'str' object has no attribute 'call'`
> 
> The function `convert_keras_model` expects a keras model, not a path to an `.h5` file. So first load the `.h5` file using Keras functions (for example `model = tf.keras.models.load_model("mnist_binary.h5")`) and then run `lce.convert_keras_model(model)` .

This gives an error `ValueError: Unknown layer: QuantConv1D`

**Comment by leonoverweel** [comment]
Did you import `larq`?

**Comment by jain-harshil** [comment]
This is my code

```
import larq_compute_engine as lce
import tensorflow as tf

tf.compat.v1.enable_eager_execution()
model = tf.keras.models.load_model("./askubuntu1.h5")
tflite_model = lce.convert_keras_model(model)
with open("./askubuntu.tflite", "wb") as f:
    f.write(tflite_model)
```

**Comment by leonoverweel** [comment]
We also don't have support for `QuantConv1D` in LCE; you can get around this by using a 1xn `QuantConv2D` instead.

**Comment by jain-harshil** [comment]
After adding line the import larq, it worked. Thanks. Thanks a lot. One last question. How do I download 8-bit precision weights?

**Comment by jain-harshil** [comment]
I mean this 
model size (8-bit FP weights): memory footprint if FP weights were 8 bit,
from https://docs.larq.dev/larq/api/models/

**Comment by leonoverweel** [comment]
We don't have support for 8-bit quantization built into Larq, since this is already [supported in TensorFlow Lite](https://www.tensorflow.org/lite/performance/post_training_quantization). We print the 8-bit quantization model size just as a convenience to see what the size would be if you used TensorFlow's tools to convert the non-binary layers to 8-bit.

**Comment by jain-harshil** [comment]
Thanks a lot for your reply.
