### ISSUE TITLE
Observation of input tensor 

### ISSUE THREAD

**Issue by PhantomClick** [larq/larq#610]
Hi,

I'm a newbie for larq and i'm worried how to obtain input tensor values after i my Conv2d applied **input_quantizer(ste_sign)** to incoming tensor to itself.

I mean my 32-bit float outputs from t-1.th layer comes to the lq.layers.QuantConv2D with input_quantizer(ste_sign), i would like to obtain 0-1 values to save them. 

Is this possible and if yes, how should i do this? 

If you could give me a hint, i'll be grateful.

Thanks

**Comment by jneeven** [comment]
Hi,

Yes, that is definitely possible! To access the quantized activations, it helps to use the quantizer as a separate layer. For example, I assume you currently have something like this:
```python
input_layer = tf.keras.layers.Input((32, 32, 3))
x = lq.layers.QuantConv2D(kernel_size=3, filters=16, input_quantizer="ste_sign")(input_layer)

model = tf.keras.models.Model(input_layer, x)
```

But what you could also do is the following:
```python
input_layer = tf.keras.layers.Input((32, 32, 3))
quantized_inputs = lq.quantizers.SteSign()(input_layer)
# TODO: save quantized inputs somewhere, e.g. with TensorBoard

# `input_quantizer=None` is the default, so we don't need to pass the argument at all if we don't want one
x = lq.layers.QuantConv2D(kernel_size=3, filters=16)(quantized_inputs)

# The resulting model is exactly the same as before, only now the input quantizer shows up as a separate layer
model = tf.keras.models.Model(input_layer, x)

Hope that helps!
```

**Comment by PhantomClick** [comment]
> Hi,
> 
> Yes, that is definitely possible! To access the quantized activations, it helps to use the quantizer as a separate layer. For example, I assume you currently have something like this:
> 
> ```python
> input_layer = tf.keras.layers.Input((32, 32, 3))
> x = lq.layers.QuantConv2D(kernel_size=3, filters=16, input_quantizer="ste_sign")(input_layer)
> 
> model = tf.keras.models.Model(input_layer, x)
> ```
> 
> But what you could also do is the following:
> 
> ```python
> input_layer = tf.keras.layers.Input((32, 32, 3))
> quantized_inputs = lq.quantizers.SteSign()(input_layer)
> # TODO: save quantized inputs somewhere, e.g. with TensorBoard
> 
> # `input_quantizer=None` is the default, so we don't need to pass the argument at all if we don't want one
> x = lq.layers.QuantConv2D(kernel_size=3, filters=16)(quantized_inputs)
> 
> # The resulting model is exactly the same as before, only now the input quantizer shows up as a separate layer
> model = tf.keras.models.Model(input_layer, x)
> ```
> 
> Hope that helps!

Yes! Your assumption fitted me exactly! I didn't know whether i can use "SteSign" as a separate layer or not. And your solution solves my problem 100%.

Have a nice day
Thank you so much
