### ISSUE TITLE
Is it possible to use Larq for n-bit Neural Nets?

### ISSUE THREAD

**Issue by sanchit-ahuja** [larq/larq#633]
Is it possible to use Larq for n-bit neural nets? I saw all the examples and quantizers for Binary Nets. Any way to use it for custom bit training?

**Comment by jneeven** [comment]
Hi! Yes, Larq can definitely be used to train networks of arbitrary bitwidth, for example using the [DoReFa quantizer](https://docs.larq.dev/larq/api/quantizers/#dorefa). You can also implement your own quantizer if you'd like, and use the existing quantizers only for inspiration. That being said, we do indeed focus on binarized networks ourselves, and the [Larq Compute Engine](https://docs.larq.dev/compute-engine/) is therefore only optimized for the binary case. If you'd like to see more higher-bitwidth functionality, feel free to make PRs!

**Comment by sanchit-ahuja** [comment]
Thanks a lot for a prompt reply! Will look into the DoReFA Quantizer or try building a custom one. Closing this issue for now.
