### ISSUE TITLE
Does Larq support conv2d_transpose?

### ISSUE THREAD

**Issue by joker-yp** [larq/larq#669]
Hi, thanks for providing Larq that makes us easier to build BNN.

I find that it seems Larq does not support conv2d_transpose yet. Do you have any plan to add transposed convolution?

**Comment by lgeiger** [comment]
> I find that it seems Larq does not support conv2d_transpose yet. Do you have any plan to add transposed convolution?

It should support transposed convolutions. Have you checked out  https://docs.larq.dev/larq/api/layers/#quantconv2dtranspose?

**Comment by joker-yp** [comment]
Ah yes. I find it.
Thank you so much.
