### ISSUE TITLE
Support for ESP32 series

### ISSUE THREAD

**Issue by Nannigalaxy** [larq/larq#676]
### Feature motivation
ESP32 series offers a good balance between affordability and performance.
Especially with ESP32-Camera module making vision-based projects cheap but unlike arm-based stm32x, there is very little firmware support in regards to run machine learning and custom ops.

Is this is in To-Do list? And when we can expect the support.

Thank you

**Comment by jneeven** [comment]
Hi! I share your interest in machine learning on the ESP32 board; I have 4 ESP32-CAM modules here myself for hobby projects. I therefore previously investigated the potential (after seeing [this TFLite blog post](https://blog.tensorflow.org/2020/08/announcing-tensorflow-lite-micro-esp32.html)) of the Xtensa ISA for LCE support, but was quite disappointed. A lot of our optimized assembly relies on the fact that on ARM architectures you often get a free shift with e.g. an `ADD` instruction, which on the Xtensa architecture is not the case. It has been quite a while, but I also believe the load instruction is less efficient. This doesn't mean that the Xtensa boards are unsuitable for neural networks though; it just means that it would require **a lot** of work from our side to get it implemented. In fact, TFLite Micro itself doesn't even have optimized kernels for the ESP32: the blog post I linked above does run on the board, but it's using the reference kernels.

Given the large amount of work required and the low industry interest in the ESP32 boards, this is therefore unfortunately not on our to-do list at all. However, if you would like to have a go at it yourself, feel free to make a PR to [Larq Compute Engine](https://github.com/larq/compute-engine) and I'd be happy to have a look!

**Comment by StuartIanNaylor** [comment]
Would the later LX7 esp32-s3 be more compatible especially with its vector instructions?

**Comment by CNugteren** [comment]
> Would the later LX7 esp32-s3 be more compatible especially with its vector instructions?

Indeed, the ESP32-S3 would be more suitable. However, we do not have this on our Larq roadmap.

Plumerai does have optimized code for the ESP32-S3, but not for the open source Larq library. If you are interested in using the ESP32-S3 with AI models commercially, please look at [our blog](https://blog.plumerai.com/2023/03/espressif_esp32-s3_support/) and contact us.
