### ISSUE TITLE
Model summary broken with TF 2.6/2.7

### ISSUE THREAD

**Issue by CNugteren** [larq/larq#726]
### Describe the bug
The Larq model summary shows 0 as  the number of MACs for a Keras MobileNetV2 network, but only since TF 2.6/2.7. With 2.5 it works fine.

### To Reproduce

Example Keras MobileNet model:
```python
import larq
from tensorflow.python.keras.applications.mobilenet_v2 import MobileNetV2

model = MobileNetV2(
    input_shape=(96, 96, 3),
    alpha=0.35,
    include_top=False,
    weights=None,
    input_tensor=None,
    pooling=None,
    classes=1000,
    classifier_activation=None,
)
larq.models.summary(model)
```

With TF 2.6.2 this yields:
```
+mobilenetv2_0.35_96 summary----------------+
| Total params                   410 k      |
| Trainable params               396 k      |
| Non-trainable params           14.1 k     |
| Model size                     1.56 MiB   |
| Model size (8-bit FP weights)  400.59 KiB |
| Float-32 Equivalent            1.56 MiB   |
| Compression Ratio of Memory    1.00       |
| Number of MACs                 0          |
+-------------------------------------------+
```

### Expected behavior
With TF 2.5.0 the output is:
```
+mobilenetv2_0.35_96 summary----------------+
| Total params                   396 k      |
| Trainable params               382 k      |
| Non-trainable params           14.1 k     |
| Model size                     1.51 MiB   |
| Model size (8-bit FP weights)  386.84 KiB |
| Float-32 Equivalent            1.51 MiB   |
| Compression Ratio of Memory    1.00       |
| Number of MACs                 10.7 M     |
+-------------------------------------------+
```
Note that almost all values have changed, not sure which values are correct though. But `Number of MACs = 0` is definitely incorrect.

### Environment

TensorFlow version: 2.5.0, 2.6.2, 2.7.0 
Larq version: 0.12.1
Python version: 3.8

**Comment by lgeiger** [comment]
I can't reproduce this bug when using `tf.keras.applications.MobileNetV2` instead of the private import from `tensorflow.python.keras.applications.mobilenet_v2`?

The private `tensorflow.python.keras` has been replaces by `keras` but the old code still exists, which can break `isinstance` checks when mixing and matching, so I expect we run into this edge case. For more info see https://github.com/tensorflow/tensorflow/issues/50613.

Let me know if this fixes it for you?

**Comment by CNugteren** [comment]
Thanks for the quick reply. Indeed, `from tensorflow.keras.applications import MobileNetV2` resolves this issue. So I guess we can indeed close this :+1:
