### ISSUE TITLE
Floating point training and evaluation for LarqZoo models

### ISSUE THREAD

**Issue by aqibsaeed** [larq/larq#778]
Hi,

Is it possible to train and evaluate LarqZoo models (e.g., QuickNet) in floating-point mode for comparison with binary counterpart?

**Comment by lgeiger** [comment]
There is no global flag in larq to disable all quantizers in larq, however you can train and evaluate a float version of quicknet, by setting the [input and kernel quantizers and the weight clipping to `None`](https://github.com/larq/zoo/blob/a216e70c95f8dfad963154c57842d6a746c20885/larq_zoo/sota/quicknet.py#L61-L71).

Keep in mind that architectures like QuickNet have been designed with binarization in mind, so they might not make a lot of sense as pure floating point models nor will they be competitive without binarization.

**Comment by aqibsaeed** [comment]
`Keep in mind that architectures like QuickNet have been designed with binarization in mind, so they might not make a lot of sense as pure floating point models nor will they be competitive without binarization.`

I was wondering the same. Thanks for the quick response.
