### ISSUE TITLE
How to avoid op ADDV2 in my model/or can the default benchmarking file support ADDV2 op?

### ISSUE THREAD

**Issue by HensonMa** [larq/larq#797]
Hi, I just got a issue about the op ADDV2. My model has the following part that I need to cast the float32 input to int8/int16/int32, then cast it back. When I cast the input to int8/int16, the final addition op changed from ADD to ADDV2 as I checked the graph. However, the default benchmarking file **lce_benchmark_model_aarch64** doesn't support ADDV2 op. Hence, how should the issue be fixed in order for dtype int8/int16, thanks!

```python
  def reshape_add(self, r, yy, method, name):
      """Match the dimension for residuals and add to activations."""
      if r is None:
          return yy
      r = tf.cast(r, tf.int16)
      out_features = yy.shape[3]
      in_features = r.shape[3]
      if in_features > out_features:
          r = r[:, :, :, :out_features]
      elif in_features < out_features:
          # assert method in ['tile', 'zeropad']
          if method == 'tile':
              ch_mult = out_features // in_features
              r = tf.tile(r, (1, 1, 1, ch_mult))
          elif method == 'zeropad':
              pad_size = out_features - in_features
              pad_width = ((0, 0), (0, 0), (0, 0), (0, pad_size))
              r = tf.pad(r, pad_width, mode = "CONSTANT")

      if yy.shape[1] != r.shape[1]:
          # r = tf.keras.layers.AveragePooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(r)
          r = r[:, :yy.shape[1], :yy.shape[1], :]

      yy_int = tf.cast(yy, tf.int16)
      sum_two = tf.add(yy_int, r)
      return tf.cast(sum_two, tf.float32)
```

### Environment

TensorFlow version: 2.9.1
Larq version: 0.12.2
Larq-compute-engine version: 0.8.0

**Comment by CNugteren** [comment]
This does not look like a Larq or [Larq Compute Engine](https://github.com/larq/compute-engine) issue to me: The TFLite converter has generated an ADDV2 op, which is indeed not supported by [TFLite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/builtin_ops.h) and therefore not by the Larq Compute Engine either.

I suggest you search for TensorFlow issues related to this, either how to avoid the ADDV2 op during conversion or how to add support for it in the TFLite run-time.
