### ISSUE TITLE
Check if quantizers with learnable parameters can be used as input and kernel quantizers

### ISSUE THREAD

**Issue by lgeiger** [larq/larq#89]
Keras has some activation layers with trainable parameters here: https://keras.io/layers/advanced-activations/

If this doesn't work (or we cannot make it work easily) this would be an argument to revisit #77

**Comment by lgeiger** [comment]
I think it would be good to at least have a unit test for this, especially once we start working on #312

**Comment by leonoverweel** [comment]
Closed in #322.
