### ISSUE TITLE
Using Larq for int8 + int1 training

### ISSUE THREAD

**Issue by Oslomayor** [larq/larq#907]
Hello everyone. I have been using Larq for a month and new to quantization training. Now, I have a pretrained BNN model where the first three layers are in float32 precision, and the subsequent layers are binary. When I observe the model's tflite file in Netron, it appears as follows:
![image](https://github.com/user-attachments/assets/6f405715-9f0a-4e98-88cb-f63b0290fcf5)

I would like to quantize the float32 layers to int8 while leaving the binary layers unchanged. How can I achieve this? I'm sure it could be implemented using Larq based on the [issue #731](https://github.com/larq/larq/issues/731) .
Are there any example codes available that demonstrate how to train an int8 + int1 model using Larq?

In my attempts, I noticed that Larq supports different quantizers, such as SteSign, ApproxSign, and DoReFa, with DoReFa allowing the specification of k_bit.

I tried using the DoReFa quantizer to quantize both activations and weights to int8. For example, is this usage correct for the first layer?
```python
# First layer
lq.layers.QuantConv2D(8, 3,
                      input_shape=(96, 96, 3),
                      input_quantizer=lq.quantizers.DoReFa(k_bit=8, mode="activations"),
                      kernel_quantizer=lq.quantizers.DoReFa(k_bit=8, mode="weights"),
                      kernel_constraint="weight_clip",
                      strides=(2, 2),
                      padding="same",
                      use_bias=True),
# Second layer
  lq.layers.QuantConv2D(16, 3,
                        input_quantizer=lq.quantizers.DoReFa(k_bit=8, mode="activations"),
                        kernel_quantizer=lq.quantizers.DoReFa(k_bit=8, mode="weights"),
                        kernel_constraint="weight_clip",
                        strides=(2, 2),
                        padding="same",
                        use_bias=True),
# ...
```
After quantization training, I obtained an h5 model that includes information about the DoReFa quantizer: 
![image](https://github.com/user-attachments/assets/628bfa27-42f2-478a-bedd-6bf990d4efd9)

However, when converting this h5 model to a tflite model, I found that the first layer's Conv2D is still in float32 precision, and several new layers appeared that were not in the original model, such as “Minimum, Relu, Mul, Dequantize, Round.”
![image](https://github.com/user-attachments/assets/f333219d-609f-4ed4-add5-016bcb6240c5)

The conversion code I used is as follows:
```python
  flatbuffer_bytes = lce.convert_keras_model(model,
                                             inference_input_type=tf.int8,
                                             inference_output_type=tf.float32,
                                             experimental_default_int8_range=(-128, 127)
                                             )
```
Could anyone please help identify where I might be going wrong? 
I would be very grateful if anyone could give me some advice on how to actually train an int8 + int1 model in Larq.

**Comment by Tombana** [comment]
Hi,
Could you try to change `lq.quantizers.DoReFa(k_bit=8, mode=...)` to Tensorflow's `fake_quant_with_min_max_args` ? I think that should make the converter do the proper int8 quantization
```python
x = tf.quantization.fake_quant_with_min_max_args(x, min=-3, max=3, num_bits=8)
```
(You might have to wrap this in a layer class to be able to use it as `input_quantizer`)

**Comment by Oslomayor** [comment]
@Tombana Thank you so much for your reply, your suggestion is very helpful.   
I used TensorFlow's `fake_quant_with_min_max_args` and wrapped it in a class to perform quantization-aware training, which successfully quantized the float32 convolutional layers in the BNN model to int8 convolutional layers. 
However, after using `lce.convert_keras_model` to convert the h5 model to tflite, I found that there are unfused mul and add operators(the red boxed area) between the two int8 convolutional layers. 
h5 modle:  
![image](https://github.com/user-attachments/assets/072b7177-1242-441a-94b2-cfeed7ce1bb3)
tflite modle:  
![image](https://github.com/user-attachments/assets/dd5c0322-dd48-42ed-b1c2-97634b8ec33c)
Is this unrelated to Larq, or is it a TensorFlow issue? Have I missed any steps? 
My codes:  
```python
# Fake Quant Layer
class FakeQuantizerLayer(lq.quantizers.Quantizer):
    def __init__(self, min_val=-3, max_val=3, num_bits=8, **kwargs):
        super(FakeQuantizerLayer, self).__init__(**kwargs)
        self.min_val = min_val
        self.max_val = max_val
        self.num_bits = num_bits
        self.precision = num_bits

    def call(self, x):
        return tf.quantization.fake_quant_with_min_max_args(
            x,
            min=self.min_val,
            max=self.max_val,
            num_bits=self.num_bits)

    def get_config(self):
        config = super(FakeQuantizerLayer, self).get_config()
        return config
```
My modle:  
```python
# First int8 layer
lq.layers.QuantConv2D(8, 3,
                      input_shape=(96, 96, 3),
                      input_quantizer=FakeQuantizerLayer(min_val=-3, max_val=3, num_bits=8),
                      kernel_quantizer=FakeQuantizerLayer(min_val=-3, max_val=3, num_bits=8),
                      kernel_constraint="weight_clip",
                      strides=(2, 2),
                      padding="same",
                      use_bias=True),
tf.keras.layers.BatchNormalization(momentum=0.9, scale=True),
# Second int8 layer
lq.layers.QuantConv2D(16, 3,
                      input_quantizer=FakeQuantizerLayer(min_val=-3, max_val=3, num_bits=8),
                      kernel_quantizer=FakeQuantizerLayer(min_val=-3, max_val=3, num_bits=8),
                      kernel_constraint="weight_clip",
                      strides=(2, 2),
                      padding="same",
                      use_bias=True),
tf.keras.layers.BatchNormalization(momentum=0.9, scale=True),
# ...
# BNN layers
# ...
```
The conversion code:  
```python
custom_objects = {
    "QuantConv2D": layers.QuantConv2D,
    "FakeQuantizerLayer": FakeQuantizerLayer,
}

model = load_model(model_name_in, custom_objects=custom_objects)
lq.models.summary(model)

# Convert our Keras model to a TFLite flatbuffer file
with open(model_name_out, "wb") as flatbuffer_file:
    flatbuffer_bytes = lce.convert_keras_model(
                                               model,
                                               inference_input_type=tf.int8,
                                               inference_output_type=tf.float32,
                                               experimental_default_int8_range=(-128, 127)
                                               )
    flatbuffer_file.write(flatbuffer_bytes)
```

**Comment by Oslomayor** [comment]
I carefully reviewed the TFLite model and, upon consideration, realized that the mul and add ops following the int8 convolution are due to my kernel using per-tensor quantization (which is done by TensorFlow's `fake_quant_with_min_max_args`). When I used `fake_quant_with_min_max_vars_per_channel` for per-channel quantization of the kernel, the generated model is exactly what I want.  Now it is perfect.
![image](https://github.com/user-attachments/assets/04897b12-67a1-49ed-adcf-3ddacbe1790f)

By the way, the paper 'Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference' is a good introductory resource on quantization for beginners like me.

Thanks @Tombana ，all of this has been inspired by you advice.

**Comment by Tombana** [comment]
Glad to hear you got it working!
