### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by Sameeksha0709** [larq/larq#909]
ttributeError                            Traceback (most recent call last)
[<ipython-input-10-250cbf17d08d>](https://localhost:8080/#) in <cell line: 2>()
      1 import tensorflow as tf
----> 2 import larq as lq

1 frames
[/usr/local/lib/python3.10/dist-packages/larq/layers.py](https://localhost:8080/#) in <module>
   1118 
   1119 @utils.register_keras_custom_object
-> 1120 class QuantLocallyConnected1D(QuantizerBase, tf.keras.layers.LocallyConnected1D):
   1121     """Locally-connected quantized layer for 1D inputs.
   1122 

AttributeError: module 'keras._tf_keras.keras.layers' has no attribute 'LocallyConnected1D'

Hi i am getting this error while i am importing the larq i am using google collab

**Comment by CNugteren** [comment]
Which version of TensorFlow and Keras are you using? Perhaps this issue only shows up with the latest version - could you try downgrading?

**Comment by Sameeksha0709** [comment]
Hi,
I am using this
tensorflow==2.10.0
keras==2.10.0
larq==0.13.0

**Comment by lgeiger** [comment]
Larq relies on TF Keras version 2 to which was deprecated in newer versions of TensorFlow.

Can you try setting the `TF_USE_LEGACY_KERAS=1` environment variable before importing larq or TensorFlow?

See the ["TensorFlow + Keras 2 backwards compatibility” section in the Keras docs](https://keras.io/getting_started/)

**Comment by Sameeksha0709** [comment]
Thanks. It's working
